"""Añadir campos educativos a Partido

Revision ID: a79eb1babd1e
Revises: ba6a40f86f3f
Create Date: 2025-04-21 10:12:45.670076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79eb1babd1e'
down_revision = 'ba6a40f86f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puntos_juego_limpio_local', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('puntos_juego_limpio_visitante', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('puntos_arbitro', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('puntos_grada_local', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('puntos_grada_visitante', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.drop_column('puntos_grada_visitante')
        batch_op.drop_column('puntos_grada_local')
        batch_op.drop_column('puntos_arbitro')
        batch_op.drop_column('puntos_juego_limpio_visitante')
        batch_op.drop_column('puntos_juego_limpio_local')

    # ### end Alembic commands ###
