"""Migración inicial

Revision ID: ba6a40f86f3f
Revises: 
Create Date: 2025-04-19 15:20:06.416173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6a40f86f3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('liga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('liga_id', sa.Integer(), nullable=False),
    sa.Column('puntos_totales', sa.Integer(), nullable=True),
    sa.Column('ganados', sa.Integer(), nullable=True),
    sa.Column('empatados', sa.Integer(), nullable=True),
    sa.Column('perdidos', sa.Integer(), nullable=True),
    sa.Column('goles_favor', sa.Integer(), nullable=True),
    sa.Column('goles_contra', sa.Integer(), nullable=True),
    sa.Column('puntos_juego_limpio', sa.Integer(), nullable=True),
    sa.Column('puntos_arbitro', sa.Integer(), nullable=True),
    sa.Column('puntos_grada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liga_id'], ['liga.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liga_id', sa.Integer(), nullable=True),
    sa.Column('equipo_local_id', sa.Integer(), nullable=True),
    sa.Column('equipo_visitante_id', sa.Integer(), nullable=True),
    sa.Column('arbitro_id', sa.Integer(), nullable=True),
    sa.Column('tutor_grada_local_id', sa.Integer(), nullable=True),
    sa.Column('tutor_grada_visitante_id', sa.Integer(), nullable=True),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visitante', sa.Integer(), nullable=True),
    sa.Column('puntos_local', sa.Integer(), nullable=True),
    sa.Column('puntos_visitante', sa.Integer(), nullable=True),
    sa.Column('finalizado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['arbitro_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['equipo_local_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['equipo_visitante_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['liga_id'], ['liga.id'], ),
    sa.ForeignKeyConstraint(['tutor_grada_local_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['tutor_grada_visitante_id'], ['equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partido')
    op.drop_table('equipo')
    op.drop_table('liga')
    op.drop_table('usuario')
    # ### end Alembic commands ###
